version: '3'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - 'prometheus_data:/prometheus'
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
            - '--web.enable-admin-api'
            - '--storage.tsdb.retention=1y'
        ports:
            - '9090:9090'
        networks:
            - prom_net

    
    node:
        image: prom/node-exporter:latest
        container_name: node 
        ports:
            - '9100:9100'
        networks:
            - prom_net
        # command:
            # - '--path.procfs=/host/proc'
            # - '--path.sysfs=/host/sys'
        depends_on:
            - prometheus
    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        networks:
            - prom_net
        volumes:
            - 'grafana_data:/var/lib/grafana'

    tomcat: 
        build: ./tomcat/
        container_name: tomcat
        depends_on: 
            - prometheus
        ports:
            - '8080:8080'
            - '8090:8090'
        networks: 
            - 'prom_net'

networks:
  prom_net:
    driver: bridge


volumes:
        prometheus_data: {}
        grafana_data: {}