{
 "title": "tomcat-monitoring",
 "description": "https://github.com/prometheus/jmx_exporter",
 "tags": [
  "JVM",
  "tomcat"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(jvm_info{namespace=~\"$namespace\",container_name!=\"POD\"},container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_bytes_used{area=\"heap\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum (jvm_memory_bytes_committed{area=\"heap\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Mem Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_bytes_used{area=\"nonheap\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum (jvm_memory_bytes_committed{area=\"nonheap\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_pool_bytes_used{pool=\"Code Cache\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum (jvm_memory_pool_bytes_committed{pool=\"Code Cache\",namespace=\"$namespace\",container=\"$container\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "Current thread connection number"
    },
    {
     "expr": "jvm_threads_started_total{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "Total number of threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "Thread peak"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "deadlocked_monitor"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "Classes that have been loaded"
    },
    {
     "expr": "jvm_classes_loaded_total{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "The sum of the load classes"
    },
    {
     "expr": "jvm_classes_unloaded_total{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "class that has been uninstalled"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_bytesreceived_total{protocol=\"http-apr\"}[10m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(irate(tomcat_bytessent_total{protocol=\"http-apr\"}[10m]))",
     "legendFormat": "output"
    }
   ]
  }
 ]
}